### ISSUE TITLE
读取mirai-api-http配置时报错

### ISSUE THREAD

**Issue by Samarium150** [YunYouJun/mirai-ts#41]
尝试使用`js-yaml`读取以下配置时报错
```yaml
adapters: 
  - http
  - ws
debug: false
enableVerify: true
verifyKey: el-psy-congroo
singleMode: false
cacheSize: 4096
adapterSettings:
  http:
      host: localhost
      port: 8080
      cors: [*]
  ws:
      host: localhost
      port: 8080
      reservedSyncId: -1
```
stacktrace如下
```
YAMLException: name of an alias node must contain at least one character at line 13, column 15:
          cors: [*]
                  ^
    at generateError (**\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
    at throwError (**\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)
    at readAlias (**\node_modules\js-yaml\lib\js-yaml\loader.js:1270:5)
    at composeNode (**\node_modules\js-yaml\lib\js-yaml\loader.js:1368:20)
    at readFlowCollection (**\node_modules\js-yaml\lib\js-yaml\loader.js:735:5)
    at composeNode (**\node_modules\js-yaml\lib\js-yaml\loader.js:1360:11)
    at readBlockMapping (**\node_modules\js-yaml\lib\js-yaml\loader.js:1089:11)
    at composeNode (**\node_modules\js-yaml\lib\js-yaml\loader.js:1359:12)
    at readBlockMapping (**\node_modules\js-yaml\lib\js-yaml\loader.js:1089:11)
    at composeNode (**\node_modules\js-yaml\lib\js-yaml\loader.js:1359:12) {
  reason: 'name of an alias node must contain at least one character',
  mark: Mark {
    name: null,
    buffer: 'adapters: \n' +
      '  - http\n' +
      '  - ws\n' +
      'debug: false\n' +
      'enableVerify: true\n' +
      'verifyKey: el-psy-congroo\n' +
      'singleMode: false\n' +
      'cacheSize: 4096\n' +
      'adapterSettings:\n' +
      '  http:\n' +
      '      host: localhost\n' +
      '      port: 8080\n' +
      '      cors: [*]\n' +
      '  ws:\n' +
      '      host: localhost\n' +
      '      port: 8080\n' +
      '      reservedSyncId: -1\n' +
      '\x00',
    position: 197,
    line: 12,
    column: 14
  }
}
```
我觉得应该`js-yaml`的问题？直接import手写的json config就能连上`mirai-api-http`
